# Generated by Django 6.1.2 on 2026-10-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_nutritionentry_alter_workout_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waist', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('thigh', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('biceps', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('calf', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
