# Generated by Django 6.1.2 on 2026-10-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='title',
            field=models.CharField(choices=[('strength', 'Силовая'), ('cardio', 'Кардио'), ('stretching', 'Растяжка'), ('swimming', 'Плавание'), ('running', 'Бег'), ('cycling', 'Велосипед'), ('other', 'Другое')], default='strength', max_length=20),
        ),
    ]
