# Generated by Django 6.1.2 on 2026-10-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_workout_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritionentry',
            options={'ordering': ['-date'], 'verbose_name': 'Nutrition entry', 'verbose_name_plural': 'Nutrition entries'},
        ),
        migrations.AlterField(
            model_name='nutritionentry',
            name='carbs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionentry',
            name='fat',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionentry',
            name='protein',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
